/**
 * One-time generator: self-host the Google Fonts used by the app so there are no
 * third-party font requests at runtime. Downloads the latin + latin-ext woff2
 * subsets and writes a local @font-face stylesheet.
 *
 * Output (committed): client/public/fonts/*.woff2 and client/public/fonts/fonts.css
 * Re-run after changing the font set:  node scripts/fetch-fonts.mjs
 *
 * Fonts are licensed under the SIL Open Font License 1.1 — see public/fonts/OFL.txt.
 */
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '..', 'public', 'fonts');

// Keep this in sync with the <link> the app/guides used to load.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400;0,6..96,500;0,6..96,600;0,6..96,700;0,6..96,800;1,6..96,400;1,6..96,500&family=Spectral:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400&family=DM+Mono:wght@300;400;500&display=swap';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

fs.mkdirSync(outDir, { recursive: true });
const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
let out =
  '/* Self-hosted web fonts — SIL Open Font License 1.1 (see OFL.txt).\n' +
  '   Generated by scripts/fetch-fonts.mjs from Google Fonts (latin + latin-ext). */\n\n';
const downloads = new Map();
let m;
while ((m = blockRe.exec(css))) {
  const subset = m[1].trim();
  if (!WANTED_SUBSETS.has(subset)) continue;
  let block = m[2];
  const urlM = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/);
  if (!urlM) continue;
  const gurl = urlM[1];
  const base = gurl.split('/').pop();
  downloads.set(base, gurl);
  out += `/* ${subset} */\n${block.replace(gurl, `/fonts/${base}`)}\n\n`;
}

let bytes = 0;
for (const [base, gurl] of downloads) {
  const buf = Buffer.from(await (await fetch(gurl, { headers: { 'User-Agent': UA } })).arrayBuffer());
  fs.writeFileSync(path.join(outDir, base), buf);
  bytes += buf.length;
}
fs.writeFileSync(path.join(outDir, 'fonts.css'), out);
console.log(`[fonts] wrote ${downloads.size} woff2 (${(bytes / 1024).toFixed(0)} KB) + fonts.css → public/fonts`);
